### ISSUE TITLE
Compile error

### ISSUE THREAD

**Issue by Tom-Shen** [moriarty/ros-ev3#10]
# I have built a test program, without add <ev3dev.h> it has no build issue, after I add <ev3dev.h>, it has many issues related ev3dev.h, can you have a look at the first several errors as below:

In file included from /home/robot/src/tj_ev3_drive/src/subscribe_to_pose.cpp:7:0:
/usr/local/include/ev3dev.h:72:37: error: in C++98 'ev3dev::INPUT_1' must be initialized by constructor, not by '{...}'
 const address_type INPUT_1  { "in1" };  //!< Sensor port 1
                                     ^
/usr/local/include/ev3dev.h:73:37: error: in C++98 'ev3dev::INPUT_2' must be initialized by constructor, not by '{...}'
#  const address_type INPUT_2  { "in2" };  //!< Sensor port 2

Thanks!

**Comment by moriarty** [comment]
I think there is a flag missing in the CMakeLists to set which c++ standard to use.

**Comment by Tom-Shen** [comment]
I mean without add ev3dev.h, the program can successfully be compiled, after add the #include <ev3dev.h>, it has lots of error. 

when I was using below command to build my test program without ROS:
g++ -o EV3ButtonTest  -std=c++11 EV3ButtonTest.cpp  ev3dev.cpp^C

the ev3dev.h has no problem.

when I was building ROS test program without ev3dev.h, it is fine.

I noticed when I was using GCC, it is c++11, for Ros it is C++98, is it root cause?

**Comment by moriarty** [comment]
```
set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -std=c++0x")
```

**Comment by Tom-Shen** [comment]
add where?

**Comment by moriarty** [comment]
Yes, for ROS it defaults to a really old version, but it can be changed easily with by adding the above line in CMakeList.txt

**Comment by moriarty** [comment]
Here is a more complete answer:

http://answers.ros.org/question/152276/is-there-a-way-to-enable-c11-support-for-catkin-packages/

**Comment by Tom-Shen** [comment]
I see, thanks!

Forgive me to always ask such low level question, I am not a professional program!

Thank you very much for your kindly help!

Thanks.
