### ISSUE TITLE
Could you help?

### ISSUE THREAD

**Issue by Tom-Shen** [moriarty/ros-ev3#13]
# recently I am installing ROS in raspberry Pi 3, I got below issue when I follow the instruction to build

==> Processing catkin package: 'collada_urdf'
==> Building with env: '/opt/ros/indigo/env.sh'
Makefile exists, skipping explicit cmake invocation...
==> make cmake_check_build_system in '/home/pi/ros_catkin_ws/build_isolated/collada_urdf'
==> make -j4 -l4 in '/home/pi/ros_catkin_ws/build_isolated/collada_urdf'
[ 33%] Built target collada_to_urdf
[ 66%] Built target collada_urdf
Linking CXX executable /home/pi/ros_catkin_ws/devel_isolated/collada_urdf/lib/collada_urdf/urdf_to_collada
/usr/bin/ld: cannot find -lcollada-dom2.4-dp
collect2: error: ld returned 1 exit status
CMakeFiles/urdf_to_collada.dir/build.make:175: recipe for target '/home/pi/ros_catkin_ws/devel_isolated/collada_urdf/lib/collada_urdf/urdf_to_collada' failed
make[2]: **\* [/home/pi/ros_catkin_ws/devel_isolated/collada_urdf/lib/collada_urdf/urdf_to_collada] Error 1
CMakeFiles/Makefile2:1467: recipe for target 'CMakeFiles/urdf_to_collada.dir/all' failed
make[1]: **\* [CMakeFiles/urdf_to_collada.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: **\* [all] Error 2
<== Failed to process package 'collada_urdf': 
  Command '['/opt/ros/indigo/env.sh', 'make', '-j4', '-l4']' returned non-zero exit status 2

Reproduce this error by running:
==> cd /home/pi/ros_catkin_ws/build_isolated/collada_urdf && /opt/ros/indigo/env.sh make -j4 -l4

Command failed, exiting.

**Comment by Tom-Shen** [comment]
I found the issue: sometimes I don know why system can not find the lib in /usr/local/lib, even it is in the conf define. so i just created a link to it.
thanks anyway!

**Comment by moriarty** [comment]
Glad you figured it out. 

FYI: GitHub uses GitHub flavoured markdown. 

https://help.github.com/articles/basic-writing-and-formatting-syntax/

By previewing your issue before you publish it- you can make it look nicer, and if it looks nicer, it's easier for people to answer and try to help.
