### ISSUE TITLE
Some question about ros_comm?

### ISSUE THREAD

**Issue by DozenCoder** [moriarty/ros-ev3#15]
Hi, I'm a newer to ROS. From the readme, we only write `ros_comm` to EV3DEV, but how we run `rosrun **.py` on the Lego Robot? We can run `roscore` in the host, but how we run ros program in client?

**Comment by moriarty** [comment]
*rosrun* is included in *ros_comm*.

*roscore* won't run on the EV3, due the hardware limitations.

the instructions only include some basic ros_msgs, but as long as your python program only uses those, you just need to export the ip of the machine where roscore is it should work.

Also: I haven't updated this project in a while, someone has forked it and dockerized it... so it may be worth trying the newer version

**Comment by moriarty** [comment]
https://github.com/osmado/ev3_wiimote

**Comment by DozenCoder** [comment]
@moriarty Thank you very much!
