### ISSUE TITLE
Everything is fine until I execute the command " ./src/catkin/bin/catkin_make_isolated --install --install-space /opt/ros/indigo -DCMAKE_BUILD_TYPE=Release"

### ISSUE THREAD

**Issue by Tom-Shen** [moriarty/ros-ev3#4]
(brickstrap)root@ubuntu:/home/ros_comm# rosinstall_generator ros_comm --rosdistro indigo --deps --wet-only --tar > indigo-ros_comm-wet.rosinstall
(brickstrap)root@ubuntu:/home/ros_comm# wstool init src indigo-ros_comm-wet.rosinstallError: There already is a workspace config file .rosinstall at "src". Use wstool install/modify.
(brickstrap)root@ubuntu:/home/ros_comm# rosdep check --from-paths src --ignore-src --rosdistro indigo -y --os=debian:jessie
All system dependencies have been satisfied
＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊
(brickstrap)root@ubuntu:/home/ros_comm# ./src/catkin/bin/catkin_make_isolated --install --install-space /opt/ros/indigo -DCMAKE_BUILD_TYPE=Release
bash: ./src/catkin/bin/catkin_make_isolated: No such file or directory**_
＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊

**Comment by moriarty** [comment]
I'm near computer,

did you do: `wstool update`?

**Comment by moriarty** [comment]
`wstool` manages workspaces, it should download the and extract the tar files specified in the indigo-ros_comm-wet.rosinstall file into their folders inside of src.

The error says it can't find catkin_make_isolated in the catkin/bin folder.

Either, the catkin folder hasn't been initialized and updated properly or the catkin_make_isolated location has changed... But I don't think it has

**Comment by moriarty** [comment]
catkin_make_isolated location hasn't changed: https://github.com/ros/catkin/blob/indigo-devel/bin/catkin_make_isolated

Check in the /home/ros_comm/src that all of the files have been downloaded and extracted correctly.

Your wstool init failed- so something likely went wrong, or you were just running the instructions again.

From inside src you can run wstool update- it will read the .rosinstall file and check to make sure all the repositories listed in it are up to date.

**Comment by Tom-Shen** [comment]
Thank you for your quick response!
Yes, I understand there is nothing currently in the folder "src".
I try to execute wstool update, it said:
(brickstrap)root@ubuntu:/home/ros_comm# ls
indigo-ros_comm-wet.rosinstall  src
(brickstrap)root@ubuntu:/home/ros_comm# wstool update  
ERROR in config: Command requires a target workspace.
(brickstrap)root@ubuntu:/home/ros_comm# wstool update src
ERROR in config: Command requires a target workspace.
(brickstrap)root@ubuntu:/home/ros_comm# 

what is the correct command?

**Comment by Tom-Shen** [comment]
Thank you sir!

********************************************************************(brickstrap)root@ubuntu:/home/ros_comm/src# ls
catkin         genlisp  message_generation  ros_comm       roslisp
cmake_modules  genmsg   message_runtime     ros_comm_msgs  rospack
gencpp         genpy    ros                 roscpp_core    std_msgs
(brickstrap)root@ubuntu:/home/ros_comm/src# 

---

Today I execute the command"wstool init src indigo-ros_comm-wet.rosinstall"  again, it behaves differently, it downloaded lots of stuff to "src" folder.

Thanks.
