### ISSUE TITLE
./src/catkin/bin/catkin_make_isolated --install --install-space /opt/ros/indigo -DCMAKE_BUILD_TYPE=Release

### ISSUE THREAD

**Issue by Tom-Shen** [moriarty/ros-ev3#5]
When I execute the command in the subject, I got below error " ROS_DISTRO was set to 'jade' before", does it related my host system, it is in Jade.

Thanks. 

---

==> cmake /home/ros_comm/src/ros/roslib -DCATKIN_DEVEL_PREFIX=/home/ros_comm/devel_isolated/roslib -DCMAKE_INSTALL_PREFIX=/opt/ros/indigo -DCMAKE_BUILD_TYPE=Release -G Unix Makefiles in '/home/ros_comm/build_isolated/roslib'
-- The C compiler identification is GNU 4.9.2
-- The CXX compiler identification is GNU 4.9.2
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Using CATKIN_DEVEL_PREFIX: /home/ros_comm/devel_isolated/roslib
-- Using CMAKE_PREFIX_PATH: /opt/ros/indigo
-- This workspace overlays: /opt/ros/indigo
-- Found PythonInterp: /usr/bin/python (found version "2.7.9") 
-- Using PYTHON_EXECUTABLE: /usr/bin/python
-- Using Debian Python package layout
-- Using empy: /usr/bin/empy
-- Using CATKIN_ENABLE_TESTING: ON
-- Call enable_testing()
-- Using CATKIN_TEST_RESULTS_DIR: /home/ros_comm/build_isolated/roslib/test_results
-- Looking for include file pthread.h
-- Looking for include file pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Found gtest sources under '/usr/src/gtest': gtests will be built
-- Using Python nosetests: /usr/bin/nosetests-2.7
-- catkin 0.6.18
-- Boost version: 1.55.0
-- Found the following Boost libraries:
--   thread
Traceback (most recent call last):
  File "/home/ros_comm/build_isolated/roslib/catkin_generated/generate_cached_setup.py", line 22, in <module>
    code = generate_environment_script('/home/ros_comm/devel_isolated/roslib/env.sh')
  File "/opt/ros/indigo/lib/python2.7/dist-packages/catkin/environment_cache.py", line 62, in generate_environment_script
    env_after = ast.literal_eval(output.decode('utf8'))
  File "/usr/lib/python2.7/ast.py", line 49, in literal_eval
    node_or_string = parse(node_or_string, mode='eval')
  File "/usr/lib/python2.7/ast.py", line 37, in parse
    return compile(source, filename, mode, PyCF_ONLY_AST)
  File "<unknown>", line 1
    ROS_DISTRO was set to 'jade' before. Please make sure that the environment does not mix paths from different distributions.
                 ^
SyntaxError: invalid syntax
CMake Error at /opt/ros/indigo/share/catkin/cmake/safe_execute_process.cmake:11 (message):
  execute_process(/usr/bin/python
  "/home/ros_comm/build_isolated/roslib/catkin_generated/generate_cached_setup.py")
  returned error code 1
Call Stack (most recent call first):
  /opt/ros/indigo/share/catkin/cmake/catkin_add_env_hooks.cmake:138 (safe_execute_process)
  CMakeLists.txt:28 (catkin_add_env_hooks)

-- Configuring incomplete, errors occurred!
See also "/home/ros_comm/build_isolated/roslib/CMakeFiles/CMakeOutput.log".
See also "/home/ros_comm/build_isolated/roslib/CMakeFiles/CMakeError.log".
<== Failed to process package 'roslib': 
  Command '['/opt/ros/indigo/env.sh', 'cmake', '/home/ros_comm/src/ros/roslib', '-DCATKIN_DEVEL_PREFIX=/home/ros_comm/devel_isolated/roslib', '-DCMAKE_INSTALL_PREFIX=/opt/ros/indigo', '-DCMAKE_BUILD_TYPE=Release', '-G', 'Unix Makefiles']' returned non-zero exit status 1

Reproduce this error by running:
==> cd /home/ros_comm/build_isolated/roslib && /opt/ros/indigo/env.sh cmake /home/ros_comm/src/ros/roslib -DCATKIN_DEVEL_PREFIX=/home/ros_comm/devel_isolated/roslib -DCMAKE_INSTALL_PREFIX=/opt/ros/indigo -DCMAKE_BUILD_TYPE=Release -G 'Unix Makefiles'

Command failed, exiting.
(brickstrap)root@ubuntu:/home/ros_comm#

**Comment by moriarty** [comment]
Sorry, I haven't tested Indigo in brickstrap on a host system with Jade. I use virtual machines and keep Jade & Indigo apart. 

There may be some environment variables set which are being carried over to your brickstrap environment.

On your host system, you can check what variables ROS is setting with `env | grep ROS` and then `unset` the variables before starting the brickstrap shell.

Another use said the instructions also work for installing Jade ros_comm on the ev3, so you could also try that.

If you try Jade keep track of any changes to the instructions :-) I'd be happy to accept a pull request with Jade instructions.

**Comment by moriarty** [comment]
You might also need to remove the build and devel folders if it started to make thinks mixed.

**Comment by Tom-Shen** [comment]
Thank your for your kind reply, this afternoon, I have followed your instruction to install the ROS under a Indigo environment, the setup is perfect, thanks, maybe later I will try to do it again in Jade environment, will tell you the result!

Thank you very much!

**Comment by moriarty** [comment]
Great, if it works I'll close this issue.

**Comment by Tom-Shen** [comment]
# @moriarty just want to tell you, today I have tried to install ROS-EV3 over the Jade, I have changed the ENV-ROS_DISTRO=jade to ROS_DISTRO=indigo, it works. 

jerrys@ubuntu:~/brickstrap$ env |grep ROS
ROS_ROOT=/opt/ros/jade/share/ros
ROS_PACKAGE_PATH=/opt/ros/jade/share:/opt/ros/jade/stacks
ROS_MASTER_URI=http://localhost:11311
ROSLISP_PACKAGE_DIRECTORIES=
ROS_DISTRO=indigo
ROS_ETC_DIR=/opt/ros/jade/etc/ros

# jerrys@ubuntu:~/brickstrap$
