### ISSUE TITLE
geometry_msgs in Brickstrap

### ISSUE THREAD

**Issue by Tom-Shen** [moriarty/ros-ev3#8]
Hello, my test program need geometry_msgs as ROS package, how can I add it to my brickstrap Ros-EV3 which currently I can not find it by rospack list?

Thanks.

**Comment by moriarty** [comment]
The instructions only install ros_comm and dependencies.

The dependencies can seen on this page:
http://wiki.ros.org/ros_comm

See my most recent answer in issue #7.
When you generate the rosinstall file, you can add the extra dependencies which you will need.

I'm in a train, and can't give much more detail than that at the moment.

**Comment by Tom-Shen** [comment]
# I just executed command like below: 

(brickstrap)root@ubuntu:/home/geometry_msgs# rosinstall_generator geometry_msgs
Using ROS_DISTRO: indigo
- git:
  local-name: common_msgs/geometry_msgs
  uri: https://github.com/ros-gbp/common_msgs-release.git
  version: release/indigo/geometry_msgs/1.11.9-0
  ================================================

What should I do for the next? can not really follow the instruction about Rosinstall 
Thanks.

**Comment by Tom-Shen** [comment]
Sorry, now I understand what you mean for step 7, I create a new workspace, I am doing the compiler.

Thanks.
