### ISSUE TITLE
Catkin_make_isolated

### ISSUE THREAD

**Issue by Tom-Shen** [moriarty/ros-ev3#9]
Hello, Sir

What is the difference between catkin_make and catkin_make_isolated in Ros-ev3?

Thanks
Jerry

**Comment by moriarty** [comment]
Hi,

Please read the ROS documentation. This questions isn't specific to the ros on the ev3.

http://wiki.ros.org/catkin
http://www.ros.org/reps/rep-0134.html

The last time I checked:
For installing the standard ros packages from source, `catkin_make_isolated` is recommended.

Once the base packages are installed, you can then create your own workspace and use `catkin_make`.

The new tool: `catkin build` is being developed but doesn't work on the EV3 and isn't recommended for use yet.

**Comment by Tom-Shen** [comment]
Thanks, Appreciated!
